import React from "react";
import { getLoginUrl } from "../lib/spotify";

/**
 * Renders the login screen for the application.
 * This component provides the user with a button to initiate
 * the Spotify authentication process. It's a purely presentational component.
 */
const LoginScreen: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-900 text-white p-4">
      <div className="text-center">
        <h1 className="text-5xl md:text-6xl font-bold mb-2 tracking-tight">
          Find-Tunes
        </h1>
        <p className="text-gray-400 text-lg mb-8">
          Your AI-Powered Music Discovery Dashboard.
        </p>

        {/* This is the core of the login component. 
          The `href` is dynamically generated by our spotify library function.
          When clicked, it redirects the user to the Spotify authorization page.
        */}
        <a
          href={getLoginUrl()}
          className="bg-[#1DB954] hover:bg-[#1ED760] text-white font-bold py-3 px-8 rounded-full text-lg transition duration-300 transform hover:scale-105 inline-block shadow-lg"
        >
          Login with Spotify
        </a>
      </div>
    </div>
  );
};

export default LoginScreen;
``;
